### ISSUE TITLE
[Feature] websocket server should have a rooms manage feature 

### ISSUE THREAD

**Issue by AdityaVerma2528** [AdityaVerma2528/ws-server#1]
index.ts should have a rooms manage feature to join a room and to create a room

**Comment by AdityaVerma594** [comment]
let me add this feature

**Comment by AdityaVerma594** [comment]
i will work on it

**Comment by AdityaVerma2528** [comment]
Great! Thanks for the contribution

**Comment by AdityaVerma2528** [comment]
thanks for the contribution
